name: CI Pipeline for Java Project

# Run workflow on push or pull requests to any branch except main/master
on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Step 3: Compile the Java code
      - name: Compile Java Project
        run: javac -d out $(find . -name "*.java")

      # Step 4: Run JUnit tests
      - name: Run Tests
        run: java -cp "out:lib/*" org.junit.runner.JUnitCore <YourTestClassName>
